nexus-data:
  image: alpine:latest
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.container.hostname_override: container_name
  entrypoint: /bin/true
  volumes:
    - /nexus-data
nexus:
  image: sonatype/nexus3
  volumes_from:
    - nexus-data:rw
  ports:
    - "8081:8081"
  labels:
    io.rancher.sidekicks: nexus-data
    io.rancher.container.hostname_override: container_name
