nexus:
  image: sonatype/nexus3
  volumes_from:
  - nexus-data:rw
  ports:
  - "8081:8081"
  labels:
    io.rancher.sidekicks: nexus-data
nexus-data:
  image: alpine:latest
  tty: true
  volumes:
  - /nexus-data
